# Copyright (c) 2022-2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# See LICENSE for license information.

[build-system]
requires = ["setuptools>=61.0", "cmake>=3.21", "wheel", "pybind11[global]", "ninja", "pip", "torch>=2.1", "jax>=0.5.0", "flax>=0.7.1"]

# Use legacy backend to import local packages in setup.py
build-backend = "setuptools.build_meta:__legacy__"

[tool.black]
line-length = 100
preview = true
enable-unstable-feature = ["string_processing"]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["transformer_engine"]
extend_skip = ["setup.py"]
